require_relative("../models/customers")
require_relative("../models/films")
require_relative("../models/tickets")
require_relative("../models/screenings")
require("pry-byebug")

Ticket.delete_all()
Screening.delete_all()
Film.delete_all()
Customer.delete_all()

customer1 = Customer.new({'name' => 'John', 'funds' => 150})
customer2 = Customer.new({'name' => 'Andy', 'funds' => 100})
customer3 = Customer.new({'name' => 'Scott', 'funds' => 50})
customer4 = Customer.new({'name' => 'Greg', 'funds' => 25})

customer1.save()
customer2.save()
customer3.save()
customer4.save()

film1 = Film.new({'title' => 'Lion King', 'price' => 25})
film2 = Film.new({'title' => 'Jungle Book', 'price' => 25})
film3 = Film.new({'title' => 'Little Mermaid', 'price' => 25})
film4 = Film.new({'title' => 'Aristocats', 'price' => 25})
film5 = Film.new({'title' => 'Hercules', 'price' => 25})
film6 = Film.new({'title' => 'Robin Hood', 'price' => 25})

film1.save()
film2.save()
film3.save()
film4.save()
film5.save()
film6.save()

screening1 = Screening.new({'film_id' => film1.id, 'show_time' => '15:00', 'capacity' => 2})
screening2 = Screening.new({'film_id' => film1.id, 'show_time' => '17:00', 'capacity' => 2})
screening3 = Screening.new({'film_id' => film1.id, 'show_time' => '20:00', 'capacity' => 2})
screening4 = Screening.new({'film_id' => film2.id, 'show_time' => '15:00', 'capacity' => 2})
screening5 = Screening.new({'film_id' => film2.id, 'show_time' => '17:00', 'capacity' => 2})
screening6 = Screening.new({'film_id' => film2.id, 'show_time' => '22:00', 'capacity' => 2})
screening7 = Screening.new({'film_id' => film3.id, 'show_time' => '16:00', 'capacity' => 2})
screening8 = Screening.new({'film_id' => film3.id, 'show_time' => '23:00', 'capacity' => 2})
screening9 = Screening.new({'film_id' => film4.id, 'show_time' => '15:00', 'capacity' => 2})
screening10 = Screening.new({'film_id' => film5.id, 'show_time' => '17:00', 'capacity' => 2})
screening11 = Screening.new({'film_id' => film6.id, 'show_time' => '19:00', 'capacity' => 2})

screening1.save()
screening2.save()
screening3.save()
screening4.save()
screening5.save()
screening6.save()
screening7.save()
screening8.save()
screening9.save()
screening10.save()
screening11.save()

ticket1 = Ticket.new({'customer_id' => customer1.id, 'screening_id' => screening1.id})
ticket2 = Ticket.new({'customer_id' => customer1.id, 'screening_id' => screening4.id})
ticket3 = Ticket.new({'customer_id' => customer1.id, 'screening_id' => screening7.id})
ticket4 = Ticket.new({'customer_id' => customer1.id, 'screening_id' => screening9.id})
ticket5 = Ticket.new({'customer_id' => customer1.id, 'screening_id' => screening10.id})
ticket6 = Ticket.new({'customer_id' => customer1.id, 'screening_id' => screening11.id})
ticket7 = Ticket.new({'customer_id' => customer2.id, 'screening_id' => screening1.id})
ticket8 = Ticket.new({'customer_id' => customer2.id, 'screening_id' => screening2.id})
ticket9 = Ticket.new({'customer_id' => customer2.id, 'screening_id' => screening3.id})
ticket10 = Ticket.new({'customer_id' => customer3.id, 'screening_id' => screening4.id})
ticket11 = Ticket.new({'customer_id' => customer3.id, 'screening_id' => screening5.id})
ticket12 = Ticket.new({'customer_id' => customer3.id, 'screening_id' => screening6.id})
ticket13 = Ticket.new({'customer_id' => customer3.id, 'screening_id' => screening7.id})
ticket14 = Ticket.new({'customer_id' => customer4.id, 'screening_id' => screening8.id})
ticket15 = Ticket.new({'customer_id' => customer4.id, 'screening_id' => screening9.id})
ticket16 = Ticket.new({'customer_id' => customer4.id, 'screening_id' => screening10.id})
ticket17 = Ticket.new({'customer_id' => customer4.id, 'screening_id' => screening11.id})

ticket1.save()
ticket2.save()
ticket3.save()
ticket4.save()
ticket5.save()
ticket6.save()
ticket7.save()
ticket8.save()
ticket9.save()
ticket10.save()
ticket11.save()
ticket12.save()
ticket13.save()
ticket14.save()
ticket15.save()
ticket16.save()
ticket17.save()

binding.pry
nil
